include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/firebase_options.dart
  errors:
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
linter:
  rules:
    public_member_api_docs: false