name: simple_chat_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  auto_route: ^5.0.2
  cloud_firestore: ^4.5.1
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_facebook_auth: ^5.0.8
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.6.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^6.1.0
  json_annotation: ^4.7.0
  json_serializable: ^6.6.1
  lottie: ^2.3.1
  sign_in_with_apple: ^4.3.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter_gen:
  output: lib/core/constants/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
